# GitHub Action metadata for giscus-bot.
#
# Two trigger modes:
#   1. Manual (workflow_dispatch): provide a blog-url to scrape
#   2. Auto (push): detects new markdown files, reads them directly from the repo

name: "giscus-bot"
description: "Generate AI discussion-starter comments for blog posts on GitHub Discussions"

inputs:
  github-token:
    description: "GitHub token with discussions:write permission"
    required: true
  provider:
    description: "AI provider to use (openai|claude|ollama)"
    required: true
  api-key:
    description: "API key for the AI provider"
    required: true
  model:
    description: "AI model to use"
    required: false
    default: "gpt-4o"
  blog-url:
    description: "Blog post URL (for manual trigger via workflow_dispatch)"
    required: false
  config-path:
    description: "Path to giscus-bot config file"
    required: false
    default: "giscus-bot.config.yaml"

runs:
  using: "node20"
  main: "action-bundle/index.js"
