# GitHub Action metadata for giscus-bot.
#
# Two trigger modes:
#   1. Manual (workflow_dispatch): provide a blog-url to scrape
#   2. Auto (push): detects new markdown files, reads them directly from the repo
#
# Example workflow:
#   - uses: your-org/giscus-bot@main
#     with:
#       github-token: ${{ secrets.DISCUSSIONS_TOKEN }}
#       provider: openai
#       api-key: ${{ secrets.OPENAI_API_KEY }}
#       blog-url: https://myblog.com/new-post

name: "giscus-bot"
description: "Generate AI discussion-starter comments for blog posts on GitHub Discussions"

inputs:
  github-token:
    description: "GitHub token with discussions:write permission"
    required: true
  provider:
    description: "AI provider to use (openai|claude|ollama)"
    required: true
  api-key:
    description: "API key for the AI provider"
    required: true
  model:
    description: "AI model to use"
    required: false
    default: "gpt-4o"
  blog-url:
    description: "Blog post URL (for manual trigger via workflow_dispatch)"
    required: false
  config-path:
    description: "Path to giscus-bot config file"
    required: false
    default: "giscus-bot.config.yaml"

runs:
  using: "node20"
  main: "dist/action-bundle/index.js"
